version: "3.8"
services:
  ab-resolver:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3000"   # TEMP for testing; remove after HTTPS works
    environment:
      NODE_ENV: production
      PORT: 3000
      # read from Portainer or .env file at runtime
      DATABASE_URL: postgres://niv:${DB_PASSWORD}@postgres:5432/ab_resolver
      # keep any other app vars you need:
      SESSION_SECRET: ${SESSION_SECRET:-dev-secret-key}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-}
    networks:
      - sharednet

networks:
  sharednet:
    external: true