version: "3.8"
services:
  ab-resolver:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3000"   # TEMP for testing; remove after HTTPS works
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://root:NM3103%40mm@postgres:5432/postgres
      - SESSION_SECRET=cf742b2c357116e42a3439f542
      - ADMIN_USER=niv
      - ADMIN_PASS=NM3103LLK6
      - ALLOWED_ORIGINS=https://opsotools.com,https://ab-resolver.opsotools.com
    networks:
      - sharednet

networks:
  sharednet:
    external: true