version: "3.8"
services:
  ab-resolver:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3000"   # TEMP for testing; remove after HTTPS works
    # Environment variables should be configured in Portainer
    # DO NOT hardcode sensitive values here!
    networks:
      - sharednet

networks:
  sharednet:
    external: true