version: "3.8"
services:
  ab-resolver:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3000"   # TEMP for testing; remove after HTTPS works
    # Pass through environment variables from Portainer
    environment:
      - NODE_ENV
      - PORT
      - DATABASE_URL
      - SESSION_SECRET
      - ADMIN_USER
      - ADMIN_PASS
      - ALLOWED_ORIGINS
    networks:
      - sharednet

networks:
  sharednet:
    external: true